### ISSUE TITLE
Development Mode - Admin Section Exception

### ISSUE THREAD

**Issue by devdesco-ceo** [ytorbyk/magento2-geo-store-switcher#1]
Installed the extension, but there are some exceptions printed out while in Development mode, when accessing Configuration section of M2:

Invalid XML in file /var/data/mfs/www/magento/app/code/Tobai/GeoStoreSwitcher/etc/adminhtml/system.xml:
Element 'frontend_model': This element is not expected.
Line: 16

#0 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Reader/Filesystem.php(117): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#1 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Data/Scoped.php(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#2 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Data/Scoped.php(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#3 /var/data/mfs/www/magento/app/code/Magento/Config/Model/Config/Structure.php(66): Magento\Framework\Config\Data\Scoped->get()
#4 /var/data/mfs/www/magento/var/generation/Magento/Config/Model/Config/Structure/Interceptor.php(14): Magento\Config\Model\Config\Structure->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#5 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Config\Model\Config\Structure\Interceptor->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#6 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array)
#7 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#8 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#9 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'configStructure', 'Magento\\Config\\...')
#10 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#11 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#12 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/ActionFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#13 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Router/Base.php(300): Magento\Framework\App\ActionFactory->create('Magento\\Config\\...')
#14 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Router/Base.php(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#15 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#18 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#20 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#23 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#24 /var/data/mfs/www/magento/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#27 /var/data/mfs/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#30 /var/data/mfs/www/magento/index.php(134): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#31 {main}

**Comment by vetalkab** [comment]
Hi Viktor,Sorry for such a long response. As for the issue with error in Magento 2 on our ToBai Geo Store Switcher extension. We have used a custom frontend model for a group in backend configuration. In the code this is permitted, but Magento 2 developers have forgotten to include it in the current release. That is why our xml doesn't pass validation. We have sent a pull request to fix this issue, but this process is to slow and currently this pull request is not accepted yet. You can apply the needed changes in your Magento 2 store by yourself to avoid this error. This is fully save and don't influence on safety of your store at all. You should add the nodes to these files: 
app/code/Magento/Config/etc/system.xsd
app/code/Magento/Config/etc/system_file.xsd
You can check our pull request to find which changes should be done here - https://github.com/magento/magento2/pull/1600. 


This should fix the issue with our ToBai Geo Store Switcher extension. Please fill free to contact us if you get any other error or questions on our extension. 

Thank you for using our products!
Vitalii Bairak


      От: Viktor Zhuromskyy <notifications@github.com>
 Кому: to-bai/magento2-geo-store-switcher <magento2-geo-store-switcher@noreply.github.com> 
 Отправлено: воскресенье, 10 января 2016 4:09
 Тема: [magento2-geo-store-switcher] Development Mode - Admin Section Exception (#1)
   
Installed the extension, but there are some exceptions printed out while in Development mode, when accessing Configuration section of M2:Invalid XML in file /var/data/mfs/www/magento/app/code/Tobai/GeoStoreSwitcher/etc/adminhtml/systemxml:
Element 'frontend_model': This element is not expected
Line: 16#0 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Reader/Filesystemphp(117): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#1 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Data/Scopedphp(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#2 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Config/Data/Scopedphp(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#3 /var/data/mfs/www/magento/app/code/Magento/Config/Model/Config/Structurephp(66): Magento\Framework\Config\Data\Scoped->get()
#4 /var/data/mfs/www/magento/var/generation/Magento/Config/Model/Config/Structure/Interceptorphp(14): Magento\Config\Model\Config\Structure->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#5 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactoryphp(103): Magento\Config\Model\Config\Structure\Interceptor->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#6 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developerphp(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Config\', Array)
#7 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/ObjectManagerphp(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Config\')
#8 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactoryphp(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\Config\')
#9 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developerphp(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\Config\', NULL, 'configStructure', 'Magento\Config\')
#10 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developerphp(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\Config\', Array, Array)
#11 /var/data/mfs/www/magento/lib/internal/Magento/Framework/ObjectManager/ObjectManagerphp(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\Config\', Array)
#12 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/ActionFactoryphp(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Config\')
#13 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Router/Basephp(300): Magento\Framework\App\ActionFactory->create('Magento\Config\')
#14 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Router/Basephp(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#15 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/FrontControllerphp(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptorphp(74): call_user_func_array(Array, Array)
#18 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chainphp(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chainphp(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#20 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidatorphp(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Chain/Chainphp(68): call_user_func_array(Array, Array)
#23 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptorphp(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali')
#24 /var/data/mfs/www/magento/app/code/Magento/Store/Model/Plugin/StoreCookiephp(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/data/mfs/www/magento/lib/internal/Magento/Framework/Interception/Interceptorphp(141): call_user_func_array(Array, Array)
#27 /var/data/mfs/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptorphp(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Httpphp(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/data/mfs/www/magento/lib/internal/Magento/Framework/App/Bootstrapphp(258): Magento\Framework\App\Http->launch()
#30 /var/data/mfs/www/magento/indexphp(134): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#31 {main}—

**Comment by devdesco-ceo** [comment]
Thanks!

**Comment by devdesco-ceo** [comment]
Any temporary solution before your pulls are merged into next magento update tag?

**Comment by ytorbyk** [comment]
Sorry for long response.
My pull request is already accepted, but still is not included into stable version.
As temporary solution you can add the same two lines into xml files which were added in the pull request.
