### ISSUE TITLE
main.CRITICAL: exception 'ErrorException' with message 'is_readable()

### ISSUE THREAD

**Issue by dwdonline** [ytorbyk/magento2-geo-store-switcher#3]
This error is causing Magento2 to give a whitescreen:

[2016-05-26 06:27:09] main.CRITICAL: exception 'ErrorException' with message 'is_readable() expects parameter 1 to be a valid path, object given' in /var/www/html/magento/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php:45
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'is_readable() e...', '/var/www/html/m...', 45, Array)
#1 /var/www/html/magento/vendor/maxmind-db/reader/src/MaxMind/Db/Reader.php(45): is_readable(Object(Magento\Framework\ObjectManager\ObjectManager))
#2 /var/www/html/magento/vendor/geoip2/geoip2/src/Database/Reader.php(52): MaxMind\Db\Reader->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#3 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(97): GeoIp2\Database\Reader->__construct(Object(Magento\Framework\ObjectManager\ObjectManager))
#4 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('GeoIp2\\Database...', Array)
#5 /var/www/html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('GeoIp2\\Database...', Array)
#6 /var/www/html/magento/app/code/Tobai/GeoIp2/Model/Database/ReaderFactory.php(64): Magento\Framework\ObjectManager\ObjectManager->create('GeoIp2\\Database...', Array)
#7 /var/www/html/magento/app/code/Tobai/GeoIp2/Model/Database/Data/Country.php(81): Tobai\GeoIp2\Model\Database\ReaderFactory->create('country')
#8 /var/www/html/magento/app/code/Tobai/GeoIp2/Model/Database/Data/Country.php(57): Tobai\GeoIp2\Model\Database\Data\Country->getReader()
#9 /var/www/html/magento/app/code/Tobai/GeoIp2/Model/Database/Data/Country.php(70): Tobai\GeoIp2\Model\Database\Data\Country->getCountry()
#10 /var/www/html/magento/app/code/Tobai/GeoStoreSwitcher/Model/GeoStore/Switcher.php(75): Tobai\GeoIp2\Model\Database\Data\Country->getCountryCode()
#11 /var/www/html/magento/app/code/Tobai/GeoStoreSwitcher/Model/GeoStoreResolver.php(80): Tobai\GeoStoreSwitcher\Model\GeoStore\Switcher->getStoreId()
#12 /var/www/html/magento/app/code/Tobai/GeoStoreSwitcher/Model/GeoStoreResolver.php(69): Tobai\GeoStoreSwitcher\Model\GeoStoreResolver->switchScope()
#13 /var/www/html/magento/vendor/magento/module-store/Model/StoreManager.php(151): Tobai\GeoStoreSwitcher\Model\GeoStoreResolver->getCurrentStoreId()
#14 /var/www/html/magento/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#15 /var/www/html/magento/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#16 /var/www/html/magento/vendor/magento/framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#17 /var/www/html/magento/vendor/magento/framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#18 /var/www/html/magento/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#19 /var/www/html/magento/vendor/magento/framework/Locale/Resolver.php(90): Magento\Framework\App\Config->getValue('general/locale/...', 'store')
#20 /var/www/html/magento/vendor/magento/framework/Locale/Resolver.php(107): Magento\Framework\Locale\Resolver->getDefaultLocale()
#21 /var/www/html/magento/vendor/magento/framework/Locale/Resolver.php(64): Magento\Framework\Locale\Resolver->setLocale(NULL)
#22 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Framework\Locale\Resolver->__construct(Object(Magento\Framework\App\Config), 'general/locale/...', 'store', NULL)
#23 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#24 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#25 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#26 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#27 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#28 /var/www/html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Cron\\Ob...')
#29 /var/www/html/magento/vendor/magento/framework/Event/ObserverFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Cron\\Ob...')
#30 /var/www/html/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(59): Magento\Framework\Event\ObserverFactory->get('Magento\\Cron\\Ob...')
#31 /var/www/html/magento/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#32 /var/www/html/magento/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('default', Array)
#33 /var/www/html/magento/vendor/magento/framework/App/Cron.php(64): Magento\Framework\Event\Manager\Proxy->dispatch('default')
#34 /var/www/html/magento/vendor/magento/module-cron/Console/Command/CronCommand.php(98): Magento\Framework\App\Cron->launch()
#35 /var/www/html/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Cron\Console\Command\CronCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Cron\Console\Command\CronCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /var/www/html/magento/vendor/magento/framework/Console/Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /var/www/html/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/html/magento/bin/magento(25): Symfony\Component\Console\Application->run()
#41 {main} [] []

**Comment by ytorbyk** [comment]
This is weird bug of magento DI. As I understood you ran di compilation and after it you didn't **`delete var/di folder`** (this was mentioned in instalation steps). For some reason it causes this bug - ObjectManager is passed to construct instead of string.
But anyway, the exeption is caught in \Tobai\GeoIp2\Model\Database\Data\Country::getCountry method.
It doesn't cause a whitescreen. I cannot reproduce the issue with whitescreen.
Could you please provide any additional settings/circumstances you use.
Thanks.

**Comment by dwdonline** [comment]
Sure, I'm trying it again. When I removed the extension, Magento worked. As soon as I installed it again, it gives the above in the log files. I'm trying an install again now.

**Comment by dwdonline** [comment]
I think I tried to upgrade it before, and it must have had a partial install of the plug. I removed and added it and that seems to have worked.
